# Generated by Django 6.0.5 on 2026-10-06 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_code', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(default='3 Years', max_length=50)),
                ('total_seats', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('available_seats', models.PositiveIntegerField(default=60)),
                ('eligibility', models.TextField(default='10+2 Higher Secondary Examination passed with minimum 50% aggregate marks.')),
                ('fees', models.DecimalField(decimal_places=2, default=45000.0, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['course_name'],
            },
        ),
    ]
